# Site
title:              Portfolio
bio:                'Portfolio of Cameron Leech-Thomson'
description:        "Portfolio of Cameron Leech-Thomson"
locale:             en_GB
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cameron-leech-thomson.github.io" # the base hostname & protocol for your site

# Comments
disqus_shortname:   default

# Social
analytics-id:       "default"
twitter:            "SLTCameron"
linkedin:           "cameron-leech-thomson"
github:             "Cameron-Leech-Thomson"

# personal
location:           Sheffield, UK
email:              cameronleechthomson@gmail.com

# Other
background_image:   /images/bg.jpg
# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss
slapform_thankyou_page: /thank-you

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
